<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="tasks.xsl"?>
<!DOCTYPE tasks [
<!ELEMENT tasks (task+)>
<!ELEMENT task (number, due-date, topic, instructions+, condition, solution, max-points)>
<!ATTLIST task subject CDATA #REQUIRED>
<!ELEMENT number (#PCDATA)>
<!ELEMENT due-date (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT instructions (instruction+)>
<!ELEMENT instruction (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
<!ELEMENT solution (#PCDATA)>
<!ELEMENT max-points (#PCDATA)>
]>
<tasks> 
	<task subject="WWW">
		<number>1</number>
		<due-date>2014-11-14</due-date>
		<topic>HTML</topic>
		<instructions>
			<instruction>Add beautiful-page.html</instruction>
			<instruction>Add style.css</instruction>
			<instruction>Add dynamic.js</instruction>
		</instructions>
		<condition>Create a full html page.</condition>
		<solution>adii.html</solution>
		<max-points>112</max-points>
	</task>
	
	<task subject="WWW">
		<number>2</number>
		<due-date>2014-11-28</due-date>
		<topic>CSS</topic>
		<instructions>
			<instruction>Add another-beautiful-page.html</instruction>
			<instruction>Add another-style.css</instruction>
			<instruction>Add another-dynamic.js</instruction>
		</instructions>
		<condition>Create a full html page.</condition>
		<solution>another-adii.html</solution>
		<max-points>150</max-points>
	</task>
</tasks>